# Production compose file for Hetzner server deployment
# Uses persistent storage on /mnt/data volume

services:
  app:
    image: quay.io/__TEMPLATE_QUAY_NAMESPACE__/__TEMPLATE_IMAGE_NAME__:latest
    ports:
      - "80:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_SECURE=true
      - APP_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=__TEMPLATE_PROJECT_SLUG__
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=__TEMPLATE_PROJECT_SLUG__
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
      - EMAIL_PROVIDER=resend
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM_ADDRESS=__TEMPLATE_EMAIL_FROM_ADDRESS__
      - EMAIL_FROM_NAME=__TEMPLATE_EMAIL_FROM_NAME__
      - APP_BASE_URL=__TEMPLATE_APP_BASE_URL__
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: docker.io/library/postgres:16-alpine
    environment:
      - POSTGRES_USER=__TEMPLATE_PROJECT_SLUG__
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=__TEMPLATE_PROJECT_SLUG__
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U __TEMPLATE_PROJECT_SLUG__ -d __TEMPLATE_PROJECT_SLUG__"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: docker.io/library/redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - /mnt/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
